rstudio/renv

DESCRIPTION
R/retrieve.R
R/tests.R
inst/resources/scripts-git-askpass.sh

No need to try and munge the URL.

provide both username + password through askpass

---

DESCRIPTION
README.md

Fix copy and paste from packrat description

replace packrat by renv

---

R/paths.R
man/paths.Rd
vignettes/renv.Rmd

APPDATA -> LOCALAPPDATA

---

R/migrate.R

To resolve #171 with most recent comment that error persisted for lib dir as well as src.

Corrected lib_dir to libDir

---

DESCRIPTION
R/pretty.R
R/utils-map.R

This avoids an error for NULL results
Fixes #https://github.com/rstudio/renv/issues/191

Collapse records before retrieving their names

---

R/dependencies.R

@kevinushey give me your thoughts on this. I tested against a real project and the combinations I could think of and all appears valid... however... I don't know what I don't know so feedback is very much appreciated. 
This is rebased on your latest commits. Addresses #235

Adding support for imports via modules::import()

---

DESCRIPTION
NEWS.md
R/config.R
R/files.R
R/globals.R
R/platform.R
R/system.R
R/temp.R
R/zzz.R
man/config.Rd
tests/testthat/test-files.R

Primarily used when copying folders to and from the cache.

allow for alternate copy methods when copying directories

---

_pkgdown.yml

Sorry for this one @kevinushey. My lack of pkgdown experience caused me to miss this with the first PR.

Add rsconnect vignette to pkgdown Articles list

---

R/python.R

close #780 
do you need NEWS item for this ?

remove duplicated python path found

---

R/available-packages.R
R/dependencies.R
R/description.R
R/filebacked.R
R/hash.R
R/install.R
R/mran.R
R/path.R
R/python.R
R/retrieve.R
R/settings.R
R/tests.R
tests/testthat/test-install.R

Closes https://github.com/rstudio/renv/issues/793.

improve handling of git subdirs

---

NEWS.md

Reading this gave me a short pause. 
Excited to try out the new release! Is #902 included?

Avoid referring to compatibility option

---

NAMESPACE
NEWS.md
R/available-packages.R
R/checkout.R
R/lockfile.R
R/pak.R
R/tests.R
man/checkout.Rd
tests/testthat/test-checkout.R

Closes https://github.com/rstudio/renv/issues/413.

implement renv::checkout()

---

R/update.R
man/update.Rd

Improve update docs

---

R/status.R
man/status.Rd

Document value that status() returns

---

vignettes/cellar.Rmd

Can install package from cellar like other sources

---

DESCRIPTION
NEWS.md
R/envvar.R
tests/testthat/test-envvar.R

Don't duplicate paths

---

R/tests.R
R/verbose.R
tests/testthat/test-checkout.R

(At least as Hadley does it)
We'll need to talk through the consequences of removing the sandbox so I can figure out where other changes are needed.

Tweaks to facilitate interactive testing

---

R/dependencies.R
R/extsoft.R
R/hydrate.R
R/init.R
R/install.R
R/load.R
R/purge.R
R/python-virtualenv.R
R/rebuild.R
R/rehash.R
R/report.R
R/restore.R
R/snapshot.R
R/update.R
R/upgrade.R
R/utils.R

This pulls out part of https://github.com/rstudio/renv/pull/1243 that handles refactoring cancellation.

use 'cancel' helper for cancellation actions

---

R/activate.R
R/cite.R
R/dependencies.R
R/install.R
R/load.R
R/modify.R
R/project.R
R/snapshot-auto.R
R/unload.R
R/upgrade.R

Similar approach to https://github.com/rstudio/renv/pull/1244.

rationalize usages of project accessors

---

R/tests.R

By handling just those packages that cause problems. Also make it so repeated calls to this function are fast.
`once()` is failing because it's somehow adjusting global options; will need #1269 to debug why.

Simplify package loading

---

R/settings.R
man/settings.Rd

* Use more markdown and title case headings.
* Make setting names headings, so they can be linked to, and bring them "above" the fold.
* Inline "Persistence" into the description.
* Suppress the non-useful format.
Fixes #1256

Polish settings docs

---

README.md

Add pronunciation guide

---

vignettes/package-install.Rmd

And how to work around it. Fixes #1201

Document that renv doesn't build vignettes

---

DESCRIPTION
tests/testthat/test-envvar.R

Now that I better understand the renv scope system

Drop withr dependency

---

tests/testthat/helper-scope.R
tests/testthat/test-vendor.R

In favour of computing directly

Eliminate renv.test.sources option

---

R/autoload.R
R/cache.R
R/cite.R
R/files.R
R/history.R
R/id.R
R/install.R
R/load.R
R/python-conda.R
R/python-virtualenv.R
R/run.R
R/scope.R
R/vendor.R
R/zzz.R
tests/testthat/helper-setup.R
tests/testthat/test-archive.R
tests/testthat/test-dependencies.R
tests/testthat/test-files.R
tests/testthat/test-install.R
tests/testthat/test-internal.R
tests/testthat/test-r.R
tests/testthat/test-retrieve.R
tests/testthat/test-snapshot.R

Use renv_scope_wd() to temporarily change working directory

---

R/activate.R
R/difftime.R
R/pretty.R
R/snapshot.R
inst/resources/activate.R
templates/template-activate.R
tests/testthat/_snaps/install.md
tests/testthat/_snaps/snapshot.md
tests/testthat/_snaps/status.md
tests/testthat/helper-setup.R
tests/testthat/helper-snapshot.R
tests/testthat/test-install.R
tests/testthat/test-snapshot.R
tests/testthat/test-status.R

Experiment using snapshots for `snapshot()` and `status()`. Uncovered one bug (use of `renv_envvar_exists()` in activate script), one small infelicity (`snapshot()` would prompt to activate even when in tests) and required a few switches from `!renv_tests_running()` to `renv_verbose()` (but maybe this is incorrect and those if statement should just be removed?).

Snapshot experiment

---

README.md
vignettes/package-install.Rmd
vignettes/package-sources.Rmd
vignettes/renv.Rmd

A few typos and very minor text suggestions I caught

renv docs review - typos and minor suggestions

---

R/equip-macos.R
R/load.R
R/python-virtualenv.R
R/python.R
R/snapshot.R
R/version.R

This is a relatively simple modification of `renv_version_components()` that makes it useful in more places.

Implement renv_version_maj_min() and use it

---

NEWS.md
R/lockfile-read.R
tests/testthat/_snaps/lockfile-read.md
tests/testthat/test-lockfile-read.R

Fixes #1027
(The error message is already much clearer than that reported in the motivating issue; this just makes it crystal clear where the problem lies.)

More informative error for `renv_lockfile_read()`

---

R/pak.R

don't try to use prebuilt pak binaries with homebrew

---

NEWS.md
R/r.R
tests/testthat/test-download.R

Closes https://github.com/rstudio/renv/issues/1359.

handle <pkg>_<sha>.zip installation

---

R/patch.R
R/path.R
R/r.R
R/utils.R
tests/testthat/helper-skip.R
tests/testthat/test-install.R

Related to https://github.com/rstudio/renv/pull/1373.

add tests for installation from zipfile

---

NEWS.md
R/dependencies.R
tests/testthat/resources/box.R
tests/testthat/test-dependencies.R

In box, `/` indicates a module, not a package

---

R/dependencies.R

* Determine project root once, and then use it for settings.
* Rearrange code and update comments to make flow a bit easier to understand

Refactor renv_dependencies_discover_description()

---

NEWS.md
R/load.R
R/lockfile.R
R/snapshot.R
man/snapshot.Rd
tests/testthat/_snaps/snapshot.md
tests/testthat/test-snapshot.R

Closes https://github.com/rstudio/renv/issues/1396.

improve handling of exclude

---

tests/testthat/test-snapshot.R

re-enable pak tests

---

R/files.R

Include process ID in backup file name

---

R/activate.R
man/activate.Rd

Document how to disable autoloader

---

vignettes/package-install.Rmd

Mention renv.download.trace in package install vignette

---

NEWS.md
R/snapshot.R
tests/testthat/test-snapshot.R

Standardize pak metadata for CRAN packages

---

NEWS.md
R/update.R
man/update.Rd
tests/testthat/test-update.R

Add update pathway for GitLab and BitBucket

---

R/vendor.R
man/vendor.Rd

Tweak vendor() docs

---

R/repair.R

https://github.com/rstudio/renv/actions/runs/5259691290/jobs/9505595748

fixup for repair

---

NEWS.md
R/project.R
man/repair.Rd
tests/testthat/_snaps/project.md
tests/testthat/test-project.R

Correctly capture empty library case

---

R/vendor.R

weally-wide metadata to avoid multi-element replacements

---

R/socket.R
tests/testthat/test-lock.R
tests/testthat/test-sandbox.R
tests/testthat/test-socket.R
tests/testthat/test-watchdog.R

I noticed on occasion the test suite would fail to start because the sandbox lock had been leaked. This PR tries to test for that.

add + tweak tests

---

R/dependencies.R
man/dependencies.Rd

Move function handling up a level and document it

---

R/dependencies.R

And introduce new renv_dependecies_scope() function

Remove remnants of old dependency caching mechanism

---

NEWS.md
R/dependencies.R
R/hydrate.R
man/dependencies.Rd
tests/testthat/test-dependencies.R

When `config$user.profile()` is `TRUE`.

Include user .Rprofile in dev dependencies

---

R/activate.R
R/init.R
R/project.R
R/restore.R
inst/resources/activate.R
man/activate.Rd
templates/template-activate.R
tests/testthat/_snaps/project.md
tests/testthat/test-project.R

Prompt to restore if `load()` finds an empty library

---

NEWS.md
R/abort.R
R/load.R
R/lockfile.R
R/restore.R
tests/testthat/test-restore.R

Closes https://github.com/rstudio/renv/issues/1474.

emit error on restore() if no lockfile

---

NEWS.md
R/install.R
R/load.R
R/pak.R
R/ppm.R
R/repos.R
R/restore.R
tests/testthat/_snaps/project.md
tests/testthat/test-ppm.R

Closes https://github.com/rstudio/renv/issues/927.
Supersedes https://github.com/rstudio/renv/pull/1420.

respect type = source with PPM

---

R/checkout.R
man/checkout.Rd
tests/testthat/test-checkout.R

Closes https://github.com/rstudio/renv/issues/1235.

use 'ppm.url' config for checkout with date

---

R/snapshot.R
tests/testthat/test-snapshot.R

Closes https://github.com/rstudio/renv/issues/1396.

fix handling of exclude in snapshot

---

NEWS.md
R/hydrate.R
R/init.R
R/settings.R
tests/testthat/_snaps/init.md
tests/testthat/test-init.R

Closes https://github.com/rstudio/renv/issues/1485.

prompt user on init if project has DESCRIPTION file

---

R/snapshot.R

Closes https://github.com/rstudio/renv/issues/1507.

depend on renv by default

---

R/snapshot-auto.R
R/snapshot.R
R/task.R
tests/testthat/_snaps/snapshot.md
tests/testthat/test-snapshot.R

Closes https://github.com/rstudio/renv/issues/1508.

tweak reporting of auto snapshot errors

---

NEWS.md
R/dependencies.R
tests/testthat/test-dependencies.R

Fix spelling/case mistake

---

NEWS.md
R/restart.R

Closes https://github.com/rstudio/renv/issues/1530.

perform 'full' session restart after activate

---

NEWS.md
R/activate.R
R/libpaths.R
R/lockfile.R
R/restore.R
tests/testthat/_snaps/activate.md

Closes #1544.
@zkamvar, are you able to test if this PR does indeed resolve your issue?

include system library in restore

---

NEWS.md
R/sandbox.R
tests/testthat/test-sandbox.R

Closes https://github.com/rstudio/renv/issues/1565.

automatically activate sandbox on load if appropriate

---

NEWS.md
inst/resources/activate.R
templates/template-activate.R

Closes https://github.com/rstudio/renv/issues/1557.

add option for startup diagnostics

---

R/upgrade.R

Closes https://github.com/rstudio/renv/issues/1546.

invoke activate in separate process

---

NEWS.md
R/autoload.R
R/imbue.R
R/metadata.R
R/r.R
tests/testthat/test-autoload.R
tests/testthat/test-profile.R

Closes https://github.com/rstudio/renv/issues/1580.

fix logic error checking autoload envvar

---

R/restart.R

Some extra insurance against https://github.com/rstudio/renv/issues/1582.

avoid multiple calls to restart in same session

---

R/activate.R

Closes https://github.com/rstudio/renv/issues/1582. I'm not sure if there's a good way to test this.

don't try to load project if already restarting

---

NEWS.md
R/dependencies.R
R/truthy.R
tests/testthat/test-dependencies.R

Closes https://github.com/rstudio/renv/issues/1558.

handle calls in chunk options

---

tests/testthat/helper-setup.R

I don't know what this does but it resolves my rate limit problem 😭

Force GH auth in test setup

---

NEWS.md
R/activate.R
R/hydrate.R
R/imbue.R
R/init.R
R/libpaths.R
R/load.R
man/hydrate.Rd
man/init.Rd
tests/testthat/helper-scope.R
tests/testthat/test-init.R

Closes https://github.com/rstudio/renv/issues/1583.

init gains load argument

---

R/dependencies.R
R/install.R
man/dependencies.Rd
man/install.Rd

Improve docs for development dependencies

---

R/libpaths.R
R/status.R
tests/testthat/_snaps/status.md

Closes https://github.com/rstudio/renv/issues/1612. PR has a couple TODO comments that I figure are worth discussing / resolving before merge.

tweak behavior of status with explicit library / lockfile

---

NEWS.md
R/utils.R
R/watchdog.R

Closes https://github.com/rstudio/renv/issues/1617.

set library path when loading renv in watchdog process

---

R/pak.R

Fixes https://github.com/rstudio/renv/issues/1577.

install 'pak' with regular renv download machinery

---

tests/testthat/test-restore.R

Closes https://github.com/rstudio/renv/issues/1570.

add test for restore + broken symlinks

---

NEWS.md
R/dependencies.R
tests/testthat/test-dependencies.R

Closes https://github.com/rstudio/renv/issues/1637.

parse top-level NAMESPACE file for deps

---

NEWS.md
R/init.R

Closes https://github.com/rstudio/renv/issues/1668.

don't prompt user if library is already empty

---

vignettes/renv.Rmd

Fixed typos and grammar in renv.Rmd.

ab-patch-typos

---

R/cache.R
R/clean.R
R/cleanse.R
R/install.R
R/load.R
R/lockfile.R
R/methods.R
R/paths.R
R/rehash.R
R/sandbox.R
R/zzz.R
tests/testthat/test-cleanse.R
tests/testthat/test-migrate.R

Closes https://github.com/rstudio/renv/issues/1682.

add helpers for cleaning up unused sandbox dirs

---

R/package.R
R/snapshot.R

Closes https://github.com/rstudio/renv/issues/1748.

avoid finding loaded packages during retrieve

---

NEWS.md
R/dynamic.R
R/retrieve.R
tests/testthat/packages/jamie/DESCRIPTION
tests/testthat/packages/kevin/DESCRIPTION
tests/testthat/packages/phone/DESCRIPTION
tests/testthat/test-install.R

check for incompatible recursive dependency versions

---

NEWS.md
R/available-packages.R
R/lockfile-write.R
R/mran.R
R/p3m.R
R/paths.R
R/record.R
R/retrieve.R
man/paths.Rd
tests/testthat/test-available-packages.R
tests/testthat/test-mran.R

Closes https://github.com/rstudio/renv/issues/1699.

support installation of historical binaries with PPM

---

NEWS.md
R/snapshot.R

fix issue with duplicated packages

---

DESCRIPTION
NEWS.md
README.md

https://github.com/rstudio/renv/issues/1826.

CRAN release 1.0.4

---

NEWS.md
R/bootstrap.R
R/load.R
R/settings.R
R/zzz.R
inst/resources/activate.R
man/settings.Rd

Fixes https://github.com/rstudio/renv/issues/1798.

use stable project ids

---

vignettes/renv.Rmd

While I was reading through the documentation I noticed a few typos or small disfluencies.

Two small typo fixes

---

R/init.R
R/lockfile.R

simplify repos handling

---

NEWS.md
R/clean.R
R/dependencies.R
R/download.R
R/parallel.R
R/retrieve.R
man/dependencies.Rd
tests/testthat/helper-testthat.R

A potential resolution for https://github.com/rstudio/renv/issues/1996.

tweak inference of repository type

---

R/upgrade.R
man/upgrade.Rd

closes #2093 
of course, open to suggestions and changes!

add documentation about what version renv::upgrade works for and alternative options

---

vignettes/rsconnect.Rmd

Saw this vignette quoted in https://github.com/posit-dev/publisher/issues/2667 and figured it was time to update the language here. I did not search the rest of the repo, just did find/replace in this file.

s/RStudio Connect/Posit Connect/

---

NEWS.md
R/bioconductor.R
R/restore.R
tests/testthat/test-restore.R

Closes https://github.com/rstudio/renv/issues/2127.

normalize Repository URLs before restore
