rstudio/renv

vignettes/renv.Rmd

Adds missing double quote around character in `renv::upgrade(version = "0.3.0-17")`.

Minor typo fix in renv.Rmd

---

DESCRIPTION
R/snapshot.R

Currently, `renv_snapshot_validate_dependencies()` can return either a logical, or a character array, if some problem is encountered.
The later results in a problem with [renv_snapshot_validate()](https://github.com/rstudio/renv/blob/master/R/snapshot.R#L133), however, when it attempts to evaluate the expression:
```r
renv_snapshot_validate_dependencies(project, lockfile, library, confirm) &&
renv_snapshot_validate_sources(project, lockfile, library, confirm)
```
With this change, any 'bad' packages detected will result in `renv_snapshot_validate_dependencies()` returning `FALSE`.

Updated renv_snapshot_validate_dependencies() to ensure that a logical result is returned

---

vignettes/docker.Rmd

Ran into this issue with Docker while attempting to follow the vignette. The `RENV_VERSION` specified with a Docker `ENV` statement will not expand inside the string passed to `RUN R -e` unless the string is enclosed in double-quotes (whereas the example used single quotes). I've changed both the `RUN R...` invocations in 71/72 to use enclosing double-quotes accordingly for consistency, though the problem is only with the `remotes::install_github()` line when actually run.
Cf. [this Docker/Moby issue](https://github.com/moby/moby/issues/9288) referencing this behavior:
> "To expand environment variables you need to use double quotes in RUN commands."
Thanks for the great package!

Docker requires enclosing double-quotes to expand env vars in strings

---

NEWS.md
R/dependencies.R
tests/testthat/test-dependencies.R

This fixes #269 by adding support for the `site` yaml field for `renv::dependencies`. 
This include test about finding non-exported function `blogdown:::blogdown_site` and exported function `bookdown::bookdown_site`
Technically you can pass a list with functions to site field but I am not sure anyone uses it. 
You can also add the yaml header in `index.md` file but I am not sure renv knows how to handle them. 
Anyway I think there could be very few people using renv and these non standard way so I left that out.

find website dependency in site yml field

---

R/paths.R

Order is now renv version, R version and platform information
https://github.com/rstudio/renv/blob/38fbe4d1c67a719afdb8c0de9f2a6295720b62b4/R/paths.R#L73
and the doc still had an example with previous ordering

correct full path example in documentation for what is appended to path

---

R/dependencies.R
tests/testthat/test-dependencies.R

Currently `modules::import` is only recognized as a dependency declaration within a `module::module` or `module::amodule` call. This misses dependencies within files used as modules, e.g., `m <- modules::use("myFileModule.R")`, where `myFileModule.R` contains top-level `modules::import` statements. 
I frequently do this b/c a file with top-level import statements can both be used as a module and be used as an input to `source()`, which make it more "portable" to those not using modules. 
I can't think of a case where `modules::import`would be called without the intention of declaring a dependency, so it seems to makes sense to remove the requirement that modules::import appear within a `module` expression...

allow modules::import outside module/amodule

---

R/rspm.R

This reduces load time in a project with a secondary CRAN repo from 4 to 1 seconds.

Fix regex for detecting RSPM URL

---

DESCRIPTION
R/python-virtualenv.R

I routinely use both Linux and Win for projects and prefer virtualenv over Conda. Restoring venv on Linux is fine, but on Win 10 I always seem to run into issues creating the venv during activation:  
```
* Creating virtual environment 'renv-python-3.8.3' ... Error: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\xxxx\\yyyyy\\2>&1'
Error: failed to create virtual environment
In addition: Warning message:
In system(cmd, intern = TRUE) :
running command '"C:/Program Files/Python38/python.exe" -m venv "C:/Users/xxxx/yyyyy/renv/python/virtualenvs/renv-python-3.8.3" 2>&1' had status 1
Traceback (most recent calls last):
17: source("renv/activate.R")
16: withVisible(eval(ei, envir))
15: eval(ei, envir)
14: eval(ei, envir)
13: local(...) at …
```

Use system2 over system in renv_python_virtualenv_create

---

NEWS.md
R/bootstrap.R
inst/resources/activate.R

Rename default extra cran url key to ensure it is not filtered out by the
repo URL deduplication code. It is thus always there as fallback in cases
where the cran url points to a server which is not available, outdated or
broken.

Increase bootstrap reliability by not filtering out extra cran url

---

R/cache.R
R/paths.R
tests/testthat/test-cache.R

Fixes https://github.com/rstudio/renv/issues/628 and adds a unit test. I've emailed the contributor agreement.
An example that uses multiple caches:
```r
mkdir <- function(path) {
if (!dir.exists(path))
dir.create(path, recursive = TRUE)
else TRUE
}
chmod <- function(path, mode = c("read", "read+write")) {
path <- normalizePath(path)
mode <- match.arg(mode)
stopifnot(file.exists(path))
numbers <- if (mode == "read") "577" else "777"
system(sprintf("chmod %s %s", numbers, path))
}
cacheDir1 <- "~/.local/share/renvTest/cache1"
cacheDir2 <- "~/.local/share/renvTest/cache2"
Sys.setenv("RENV_PATHS_CACHE" = paste(cacheDir1, cacheDir2, sep = ";"))
Sys.getenv("RENV_PATHS_CACHE")
renv::paths$cache()
sapply(renv::paths$cache(), unlink, recursive = TRUE)
sapply(renv::paths$cache(), mkdir) …
```

Support multiple caches

---

R/cache.R

So we played around a bit with multiple caches and unfortunately, it looks like my previous PR (#653) introduced a bug. This PR hopefully solves that. The problem is that some callers of `renv_cache_find` really expect a single string but this code
```r
if (!is.null(record$Hash)) {
path <- with(record, renv_paths_cache(Package, Version, Hash, Package))
return(path)
}
```
always returns multiple strings if there are multiple caches. This mainly occurs when calling `renv::restore`, or when passing a record to `renv::install`.
Below some example code that does not retrieve an installed package from the cache but instead downloads it anew. We also encountered situations where for some packages an error was thrown, but I think the many warnings speak for themselves. 
```r
mkdir <- …
```

Fix detection of caches with hashes

---

vignettes/local-sources.Rmd

Thanks for this nice package.  This PR fixes a typo in the `vignette/local-sources.Rmd`.

fix a typo in the local-sources vignette

---

DESCRIPTION
R/settings.R
man/settings.Rd

Added missing documentation in `?renv::settings` (see #696).

added missing documentation entry for 'vcs.ignore.local'

---

DESCRIPTION
R/snapshot.R

I noticed that **renv** can complaints if you have non-package subfolders in your library path, e.g.
```r
Project '~/test' loaded. [renv 0.13.2]
The following package(s) are missing their DESCRIPTION files:
    _foobar [/home/hb/test/renv/library/R-4.0/x86_64-pc-linux-gnu/_foobar]
These may be left over from a prior, failed installation attempt.
Consider removing or re-installing these packages.
```
This PR fixes that by ignoring folders that cannot be packages. This also removes the need for hardcoded filters, such as the one used to drop subfolders named `_cache`.

Keep only library path subfolders that are valid R package names

---

R/path.R

I sadly enough cannot give an easily reproducible example of the problems we ran into.
But using this hack that is apparently only necessary on R<4 causes our application (with embedded R) to choke windows somehow. And if the hack isn't necessary anyhow than we prefer not using it at all.

Removes the path->shortpath normalizePath hack when R version >= 4.0.0

---

R/session.R

Because they just mean to suppress the startup message
```
-q, --quiet           Don't print startup message
--silent              Same as --quiet
```
Not sure if it is the best way to handle #733, but this is a solution.

stop detecting --quiet and -q

---

NEWS.md
R/dependencies.R
R/files.R
tests/testthat/resources/utility
tests/testthat/test-dependencies.R

Implements #801 
If a file has no file extension, this PR adds code that opens the file in binary mode and reads the first two bytes; if these bytes are equal to `#!`, it continues to read the first line and checks whether it contains the word `R`, `r` or `RScript`. If so, this file is treated as an R script file.
For now this PR does *not* check whether the file is executable, since file executability is not a cross-platform property, which would thus lead to different results of `renv::dependencies()` across platforms (in particular, `file.access` does not consider file mode flags on Windows; instead, it tests for specific file extensions).
I’m unsure whether the helper function location (in `R/dependencies.R`) is correct within the project’s scope: maybe they should instead go into …

Add dependency discovery support for utility scripts

---

R/consent.R

In similarity to using a docker container, this pull request adds a test for the `/.singularity.d` directory in a singularity container, to provide implicit consent.
Thanks for considering this.

Using a singularity container is implicit consent

---

R/renvignore.R
tests/testthat/test-renvignore.R

Closes https://github.com/rstudio/renv/issues/863.
This PR allows one to set `.renvignore`-style ignores for `renv` via the option `renv.renvignore.exclude`. These can either be `.gitignore`-style ignores, or (if the `asis` attribute is set to `TRUE`) PCREs which match against the full file path. (Directories will have a trailing `/` appended to the path.)
The option is primarily intended for internal consumption, so I haven't documented any explicit interface here.
I think the usage for Packrat here would be something like:
```
ignores <- packrat::opts$ignored.directories()
attr(ignores, "asis", TRUE) <- TRUE
options(renv.renvignore.exclude = ignores)
```
Let me know if this seems sane.

allow renv ignores to be set via option

---

DESCRIPTION
R/remotes.R
tests/testthat/test-remotes.R

The main reason where standard url check not working is `Remotes` section in `DESCRIPTION` file where spec contains `url::`.
```
Remotes: 
url::https://github.com/kevinushey/renv.git1/archive/refs/heads/main.zip
```
It also possible to solve this in simple way by replace in spec. [[1]](https://github.com/galachad/renv/tree/handling-ulr-simple)
```
spec <- sub("^url::", "", spec)
```

Handling url remotes from DESCRIPTION

---

R/paths.R

`RENV_PATHS_LOCKFILE` was missing for some reason in the corresponding table of env vars.

document `RENV_PATHS_LOCKFILE`

---

DESCRIPTION
NEWS.md
R/paths.R
R/rtools.R
renv.Rproj

Fixes #1002
- Identify Rtools 4.2 when installed
- Update compatibility to indicate that Rtools 4.2 should be used for R >= 4.2
- Set `BINPREF` to `""` when using Rtools 4.2
- Handle RENV_PATHS_RTOOLS environment variable correctly

Fix handling of Rtools 4.2

---

R/libpaths.R

In R CMD check for R >= 4.2, the environment variable R_LIBS_USER somehow gets set to the character NULL.
This is a bandaid for this. See https://github.com/rstudio/renv/issues/1161#issuecomment-1461092077

prevent "NULL" user libpaths

---

vignettes/ci.Rmd

Closes #944 
This rewrites the part about CI with github action to point and promote usage of `r-lib/actions/setup-renv`

Add mention of `rlib/setup-renv` in CI article

---

vignettes/ci.Rmd

* Make it more clear why you'd want to use renv on CI, and why it's not a good idea for CRAN packages
* Flip order of renv approaches (since IMO r-lib/setup-renv is easiest for most people)
* Remove travis, since few people in the R community are using it any more.

Tweaks to CI vignette

---

.github/workflows/pkgdown.yaml
DESCRIPTION
_pkgdown.yml

I also used the tidytemplate template, which despite the name, is something we use for many non-tidyverse Posit packages. It's a pretty minor variation from the default, but I do think it looks little cleaner.

Build & deploy pkgdown site automatically

---

R/utils.R

So we match the behaviour in non-interactive sessions (or when `prompt` has been set to `FALSE`).
Fixes #1240
(Hopefully this PR is easier to review 😆)

Proceed by default

---

R/pretty.R
R/retrieve.R
R/tests.R
R/utils-format.R
tests/testthat/helper-aaa.R
tests/testthat/test-bioconductor.R
tests/testthat/test-description.R
tests/testthat/test-init.R
tests/testthat/test-install.R
tests/testthat/test-repair.R
tests/testthat/test-restore.R
tests/testthat/test-snapshot.R

Since `renv_verbose()` now automatically suppresses output during tests

Eliminate renv_tests_verbose()

---

R/tests.R
tests/testthat/test-available-packages.R
tests/testthat/test-bioconductor.R
tests/testthat/test-hash.R
tests/testthat/test-install.R

Now that `renv_tests_root()` is no longer required in `tests/testhat.R` we can use `testthat::test_path()`.
I also removed the interactive working directory change when using RStudio, since in general that shouldn't be necessary. But I don't know why it was there in the first place, so I might be wrong.

Simplify path handling in tests

---

R/diagnostics.R
R/hash.R
R/load.R
R/lockfile.R
R/pretty.R
R/records.R

`csort()` now is the only place that uses `renv_scope_locale()`, so I could simplify/inline that logic too, if you wanted.

Use `csort()` in more places

---

DESCRIPTION
R/bootstrap.R
R/dependencies.R
R/filebacked.R
R/index.R
R/memoize.R
R/mran.R
R/scope.R
R/update.R
tests/testthat/setup.R

This is the first step towards unifying `%||%` and `%??%`. After a few abortive attempts, I figured out the best way to do this is to slowly move usage of `%||%` to `%??%`, since that makes it stricter. Then, once that's all done, I can rename `%??%` to `%||%`.
This first PR eliminates the use of `%||%` with environments by using argument defaults more in `scope.R`, and using `%??%` for environment caching elsewhere.
This includes a temporary warning in `%||%` and a temporary elimination of `warn = 1`. If you think this first step is sound, I'll remove these changes prior to merging.

Eliminate use of %||% with environments

---

R/utils.R
tests/testthat/test-utils.R

To avoid future confusion. Part of `%||%`/`%??%` tidy up.

Eliminate `%NULL%`

---

tests/testthat/helper-scope.R

To avoid caching in `renv_paths_root_default()`

Use RENV_PATHS_ROOT in test-setup

---

R/utils.R
tests/testthat/helper-scope.R
tests/testthat/test-envvars.R

Includes `rep_named()` helper ported from rlang, which makes generating a named list of NULLs a bit easier.

Only temporarily unset RENV_CONFIG_*

---

DESCRIPTION
R/remotes.R
tests/testthat/helper-scope.R
tests/testthat/helpers-skip.R
tests/testthat/test-install.R
tests/testthat/test-retrieve.R
tests/testthat/test-update.R

* Provide standardised helper
* No generic skip on 403 to force confrontation of problems
* Use gitcreds

Tweak handling of GitHub auth

---

R/defer.R
tests/testthat/helper-scope.R

This allows you to reset the state after running (e.g.) `renv_tests_scope()` interactively.

Provide helper to execute deferred handlers interactively

---

R/bootstrap.R
inst/resources/activate.R
templates/template-activate.R
tests/testthat/_snaps/bootstrap.md
tests/testthat/test-bootstrap.R

This is partly an exploration of using snapshot tests, and partly some minor fixes to the bootstrap output.
Part of #353
Boostrapping a project now looks like this:

Polish bootstrapping output

---

R/dependencies.R
R/download.R
R/scope.R
R/update.R
tests/testthat/test-sandbox.R
tests/testthat/test-scope.R

* Makes environment to be modified the first argument
* Calls the environment that defined the scope the `frame` (since technically it must be an environment that corresponds to a call frame)
* Add some tests
* Use in `renv_download_default_agent_scope_impl()`

Replace renv_scope_var() with renv_scope_binding()

---

NEWS.md
R/snapshot.R
tests/testthat/_snaps/snapshot.md
tests/testthat/test-snapshot.R

Even if there are no changes to packages. Fixes #962

Always show R version changes in snapshot

---

R/equip.R
_pkgdown.yml
man/equip.Rd
vignettes/package-sources.Rmd
vignettes/renv.Rmd

Fixes #1264. Closes #346. Closes #108.
@kevinushey I wasn't sure exactly what you were thinking here, but this should be a good start at making `equip()` less prominent in the docs. Let me know if there's anything specific you'd like me to say in the equip docs.

Demphasise equip

---

R/scope.R
tests/testthat/_snaps/preflight.md
tests/testthat/test-clean.R
tests/testthat/test-preflight.R
tests/testthat/test-python.R
tests/testthat/test-rebuild.R
tests/testthat/test-restore.R
tests/testthat/test-update.R
tests/testthat/test-utils.R
tests/testthat/test-vendor.R

I don't think it's been routinely needed for a while (since `renv_verbose()`) and the remaining uses have been superseded by snapshotting.

Eliminate renv_scope_sink()

---

NEWS.md
R/pretty.R
R/status.R
tests/testthat/_snaps/status.md
tests/testthat/test-status.R

* Use `renv_print_records_pair()` for {up,down,cross}grades
* Use matching bulleted list for other cases
Fixes #675. Built on top of #1365

Tweak display of status

---

R/abi.R
R/cache.R
R/ci.R
R/cite.R
R/clean.R
R/equip-macos.R
R/extsoft.R
R/hydrate.R
R/install.R
R/library.R
R/load.R
R/lockfile-read.R
R/modify.R
R/pretty.R
R/purge.R
R/python-virtualenv.R
R/rehash.R
R/retrieve.R
R/snapshot.R
R/tests.R
R/update.R
tests/testthat/_snaps/install.md
tests/testthat/_snaps/preflight.md
tests/testthat/_snaps/pretty.md
tests/testthat/_snaps/snapshot.md
tests/testthat/_snaps/status.md
tests/testthat/test-pretty.R

* All calls either do set `wrap = FALSE` or (IMO) should set `wrap = FALSE`
* Use `-` instead of tab to make a bulleted list
* The emitter argument didn't have any affect

Eliminate emitter and wrap arguments

---

R/snapshot.R
tests/testthat/_snaps/snapshot.md
tests/testthat/test-snapshot.R

This was motivated by #1198 where in one of the examples I noticed:
```
NOTE: Dependency discovery took 11 seconds during snapshot.
Consider using .renvignore to ignore files -- see `?dependencies` for more information.
```
That occurs because the current code includes time spent waiting for the prompt. That seemed like a potentially confusing red herring to me , so I moved the time tracking to `renv_snapshot_filter_implicit()`. I think this is correct as (a) it's the only type that's likely to be slow and (b) it's the only type affected by `.renvignore`.

Only report slow dependency discovery for implicit type

---

R/bioconductor.R

This is now needed so you don't get an additional prompt that `prompt` argument to `install()` doesn't affect. There might be a better way to handle this, but this is a quick fix to resolve the issue.

Don't prompt when automatically installing BiocManager

---

R/description.R
R/install.R
R/project.R
tests/testthat/test-install.R
tests/testthat/test-profile.R

Now we first discover all dependencies then update those generic records with specifics found in the `DESCRIPTION`.

Refactor dependency handling in install()

---

vignettes/package-install.Rmd

`renv.auth` option for specific package could be set as a list, but also as a function with single argument record, similarly, but not exactly the same, to general renv.auth function.
I had a case where passing the option as a function was the most convenient solution, and I'd appreciate if this was explicitly listed as a viable alternative in vignette. Hope it's not some unrecommended solution or anything.

Add example for setting renv.auth per package as function

---

R/checkout.R
R/clean.R
R/dependencies.R
R/diagnostics.R
R/embed.R
R/graph.R
R/snapshot.R
tests/testthat/test-dependencies.R

* Previously the `dev` argument did nothing, but the default make it seem like dev deps would have been filtered out.
* Systematically use `renv_dependencies_impl()` instead of `dependencies()`
* Implementing `renv_dependencies_impl()` allows us to return a single field while filtering for dev deps.

Implement dev filtering in `renv_dependencies_impl()`

---

NEWS.md
R/dependencies.R
R/description.R
R/package.R
R/project.R
R/retrieve.R
R/settings.R
man/dependencies.Rd
man/settings.Rd
tests/testthat/test-dependencies.R
tests/testthat/test-install.R

* Top-level `DESCRIPTION` is now treated the same way regardless of whether it's a "Package" or not.
* `settings$package.dependency.fields()` no longer affects transitive dependencies.
* Document how "development dependencies" are found in `dependencies()`

Simplify handling of `Suggested` dependencies

---

R/utils.R
tests/testthat/_snaps/install.md
tests/testthat/_snaps/snapshot.md
tests/testthat/_snaps/status.md

* Use - instead of =
* Use console width (up to 78 characters)

Tweak header() formatting

---

R/vendor.R
man/vendor.Rd

This ensures that venodoring works with the change from tags to shas.

Switch out vendoring to use renv_bootstrap_download_tarball()

---

R/status.R
tests/testthat/_snaps/bioconductor.md
tests/testthat/helper-scope.R
tests/testthat/helper-snapshot.R
tests/testthat/test-bioconductor.R

Includes new `renv_tests_scope_system_cache()` to make it easier to install packages from the system cache to speed up performance in tests.
Fixes #1356

Only add BiocManager as dep when used

---

R/bootstrap.R
R/vendor.R
tests/testthat/_snaps/bootstrap.md

Traps download failures, as we were attempting to `untar(FALSE)` before. Default the vendor version to the current renv version. Print the version when downloading from GitHub.
This lets me successfully:
```
remotes::install_github("rstudio/renv", "aron-vendor-untar-fix")
renv:::vendor()
```
Feel free to discard/reimplement if the intent was some other interaction with `vendor`.
Fixes #1418
Note: Rooted on https://github.com/rstudio/renv/pull/1407 because that's the change I wanted to use.

vendor: default version and trapped download failures

---

R/memoize.R
R/migrate.R
R/package.R
R/paths.R
R/restore.R
tests/testthat/helper-setup.R

To verify everything looks ok, I created https://github.com/hadley/renvdep, which errors with `renv:::renv_paths_root()` in both an example and a test. That confirms the root path uses the temp directory, which I think should be enough to close #1298.

Refactor `renv_package_checking()`

---

NEWS.md
R/dependencies.R
R/download.R
R/project.R
R/scope.R
R/snapshot.R
R/update.R
tests/testthat/test-scope.R

Closes https://github.com/rstudio/renv/issues/812.
Also flips around the arguments in `renv_scope_binding()` -- I think you might have advocated for this previously?

dont check repos in synchronized check

---

R/install.R

Since download time is reported elsewhere, and the previous approach included time spend waiting for the user.

Report on just the install time

---

R/clean.R
R/condition.R
R/dependencies.R
R/hydrate.R
R/init.R
R/snapshot.R

* Instead of `renv_dependency_scope()` we now have `renv_dependency_confirm()`
* Only `init()` caches dependency computation, and it's now explicit

Rework dependency prompting and init caching

---

R/pretty.R
tests/testthat/test-pretty.R

Closes https://github.com/rstudio/renv/issues/1413.
@hadley @juliasilge: this PR brings back the previous behavior; do you think this is sufficient or should we consider an alternate mechanism for customizing how messages are printed?

support optional pretty print emitter

---

R/dependencies.R

This takes the run-time of `renv::dependencies()` on renv its from 3s down to 0.1s, where ~75% of the remaining time is from `file.info()`.
There is one possible drawback to the current implementation. Because problems are emitted as a side-effect, they're not replaced by the cache so you'll only see them the first time the file is processed. But OTOH, it's nice to only be warned about problems once per session, rather than every time.
If you want me to fix this, I think it'll require that the individual `renv_dependencies_discover_*` callbacks return a list of dependencies and problems.

Cache dependencies per file

---

R/load.R
R/rstudio.R

Since the entire bootstrapping operation is now called inside a `sessionInit` hook when needed.

Call post-load user feedback functions directly

---

R/difftime.R
R/download.R
R/imbue.R
R/install.R
R/restore.R
R/retrieve.R
R/snapshot.R
R/utils.R
tests/testthat/_snaps/bioconductor.md
tests/testthat/_snaps/install.md
tests/testthat/_snaps/lockfile-read.md
tests/testthat/_snaps/snapshot.md
tests/testthat/helper-snapshot.R
tests/testthat/test-init.R

IMHO the extra spacing makes things a bit cleaner, and matches the spacing we use in "standard" pretty print outputs.
```
> renv::install(c("tidyverse", "dplyr"))
[no downloads required]
The following package(s) will be installed:
- dplyr     [1.1.2]
- tidyverse [2.0.0]
Do you want to proceed? [Y/n]: y
Installing dplyr     ... OK [copied from cache]
Installing tidyverse ... OK [copied from cache]
Successfully installed 2 packages in 0.13 seconds.
```

extra spacing in installation output

---

R/activate.R
R/bootstrap.R
R/init.R
R/metadata.R
R/patch.R
R/snapshot.R
R/utils.R
inst/resources/activate.R
tests/testthat/_snaps/bootstrap.md
tests/testthat/test-bootstrap.R
tests/testthat/test-metadata.R

Also removes `renv_metadata_is_dev()` as we should be consistently setting both `version` and `sha` in the `renv` metadata. We still need the bootstrap equivalents; I'd like to get rid of that requirement but that's hard to unravel.

tweaks to bootstrap output display

---

R/download.R
R/remotes.R
tests/testthat/helper-setup.R

* Do it as required (so it's when calling renv from other packages)
* Use it when retrieving DESCRIPTION

Tweak GitHub auth

---

R/init.R
tests/testthat/test-init.R

Since some R installations (from the default Linux OS package manager) might set a default R repository for the user.

replace default RStudio mirrors with PPM

---

NEWS.md
R/checkout.R
R/lockfile-write.R
R/snapshot.R
man/checkout.Rd

This makes it easier to create an `renv` lockfile directly from some repository + some set of packages, without needing to install those packages first. (The downside is you don't get the package hashes in the lockfile.)

checkout actions

---

R/load.R
R/report.R
R/snapshot-auto.R
R/snapshot.R
tests/testthat/test-snapshot.R

Closes https://github.com/rstudio/renv/issues/1536. In essence, if an automatic snapshot would have prompted the user for installation of missing packages, we just cancel the automatic snapshot.
This might warrant some more consideration of when it's safe to perform an automatic snapshot.

allow cancel of auto snapshot

---

R/install.R
R/pretty.R
R/restore.R
R/retrieve.R
tests/testthat/_snaps/bioconductor.md
tests/testthat/_snaps/init.md
tests/testthat/_snaps/install.md
tests/testthat/_snaps/load.md
tests/testthat/_snaps/preflight.md
tests/testthat/_snaps/pretty.md
tests/testthat/_snaps/snapshot.md

I ended up changing my mind 🙃  I think having compact output gives a natural separation between the "stages" of installation.
```
> renv::install(c("tidyverse", "dplyr"))
- Downloading tidyverse from CRAN ...           OK [418.4 Kb]
- Downloading dplyr from CRAN ...               OK [1.5 Mb]
Successfully retrieved 2 packages in 1.7 seconds.
The following package(s) will be installed:
- dplyr     [1.1.2]
- tidyverse [2.0.0]
These packages will be installed into "~/Library/R/arm64/4.3/library".
- Installing dplyr ...                          OK [installed binary and cached in 0.57s]
- Installing tidyverse ...                      OK [installed binary and cached in 0.51s]
Successfully installed 2 packages in 1.2 seconds.
```

try compact output

---

R/dependencies.R
R/install.R
R/retrieve.R
tests/testthat/packages/bread/DESCRIPTION
tests/testthat/test-install.R

Closes https://github.com/rstudio/renv/issues/1336.
It seems like 'dependencies' can be used for two different meanings:
1. Controlling which subset of packages get installed from the package DESCRIPTION file;
2. Controlling which (custom) fields are used when installing packages and their dependencies.
For (1), if you specify `renv::install(dependencies = "Imports")`, I think we should only take the Imports of the top-level DESCRIPTION file, but still use `c("Depends", "Imports", "LinkingTo")` for the dependencies of those packages.
For (2), I think we should propagate the "custom" dependency fields. So, for example, if you use:
```
renv::install("toast", dependencies = "Config/Needs/protein")
```
And we have this dependency graph:
```
toast -> bread -> [Config/Needs/protein: egg]
``` …

tweak handling of dependencies

---

R/activate.R
R/lockfile.R
R/snapshot.R
R/utils.R
tests/testthat/test-snapshot.R

Closes https://github.com/rstudio/renv/issues/1559.
This PR tweaks when and how we report packages with unknown sources. In particular, we now only report those sources when creating a lockfile via a top-level call to `snapshot()`.
Honestly though, I'm starting to think it's not worth it for us to try and "fix" the remote source for packages installed from local sources like this.

tweak how missing packages / unknown sources are reported

---

NEWS.md
R/available-packages.R
man/repair.Rd
tests/testthat/test-available-packages.R
tests/testthat/test-install.R

Closes https://github.com/rstudio/renv/issues/1578.

tolerate errors when querying available packages

---

R/upgrade.R
man/upgrade.Rd
tests/testthat/test-upgrade.R

And use better test for version

Make upgrade quieter

---

R/bootstrap.R
inst/resources/activate.R
templates/template-activate.R

Since right now, in an `renv` project:
```
$ R -s -e 'ls()'
[1] "flush_console"
```

avoid leaking flush_console definition

---

NEWS.md
R/dependencies.R
R/snapshot.R
R/status.R
tests/testthat/_snaps/dependencies.md
tests/testthat/test-dependencies.R

Closes https://github.com/rstudio/renv/issues/1573.

notify user if directory contains lots of files on load

---

R/clean.R
R/hydrate.R
R/install.R
R/lockfiles.R
R/pretty.R
R/purge.R
R/rebuild.R
R/rehash.R
R/restore.R
R/roxygen.R
R/scope.R
R/snapshot.R
R/update.R
R/upgrade.R
man/record.Rd
man/restore.Rd
man/status.Rd

Since the output we display might be controlled by `renv.verbose`.

be verbose if we're going to prompt

---

NEWS.md
R/download.R
tests/testthat/helper-setup.R
tests/testthat/test-install.R

Closes https://github.com/rstudio/renv/issues/1605.

avoid duplicating auth headers with libcurl

---

DESCRIPTION
NEWS.md
R/lockfile.R
R/snapshot.R
R/status.R
man/snapshot.Rd
man/status.Rd

Hi,
we used to use `renv::snapshot(type = "explicit")` to capture all dependencies stated in the DESCRIPTION file for package development. We put all packages we need for CICD to *Suggests*, as they are not required for a working package API.
During CICD pipelines, we used `renv::restore()` for installing all packages we need.
After the recent update to v1.0.0 we basically ran into the same issue as described here:
https://github.com/rstudio/renv/issues/1019#issuecomment-1644266879
We don't like the idea of putting all CICD required packages into *Imports*. Instead, we propose to expose the option to  record *dev* dependencies in the snapshot (and to consider them in checking the project status with `renv::status()`).
Please have a look. Thanks.

Explicit snapshot

---

NEWS.md
R/bootstrap.R
R/load.R
inst/resources/activate.R
templates/template-activate.R

Closes https://github.com/rstudio/renv/issues/1650.

fix issue with autoloader in RStudio

---

R/pak.R

If there are no remotes to restore, then `pak$pkg_install(remotes)` hangs. We simply return early now if that is the case.
You can reproduce the bug as follows:
1. Create a codespace using the `rocker-no_bioc` branch in `MiguelRodo/TestRenv` (`pak` enabled, `BioConductor` reference removed from lock file and no other dependencies).
2. Run `R` in the terminal.
3. Agree to restore. `pak` will be installed, and then you will get `Subprocess is busy or cannot start` error.
4. Now in regular R terminal, run `renv::restore()`. It will hang, and show that it's installing `0/0` packages.
Stepping through `renv_pak_restore` showed that this happened when the `remotes` variable passed to `pak$pak_install` was empty. We now check for the length of `remotes`, and return `invisible(TRUE)` if it's …

Return early if there are zero remotes to restore

---

R/snapshot.R
man/lockfiles.Rd
man/snapshot.Rd

Thanks for such a great package.
This just adds the missing double quote to the end of the `"custom"` `type` in the `snapshot()` helpfile code. I also reran `devtools::document()`.

Add closing double quote in a helpfile option

---

R/init.R

Hi,
This PR fixes a single typo in the `init()` function's roxygen documentation, which flows into the pkgdown site.
Thank You,
-- Michael

Fixed typo in `init()` documentation

---

NEWS.md
R/autoload.R
R/load.R
R/lockfile-diff.R

Closes https://github.com/rstudio/renv/issues/1683.

avoid false positive for packages installed without known source

---

R/files.R

Hello,
I use `renv` in a secure environment, and have run into an issue where `renv` fails to initialise because of permissions errors from `cp -pPR ...`.
Reason: the `source` directory from which `renv` copies from (set by `renv_namespace_path("renv")` or `renv_package_find("renv")` during `renv_imbue_self()`) is not owned by me, and hence I do not have permission to copy preserving permissions. I don't think my setup is *especially* unusual, so I imagine others might run into this problem.
A workaround for me was to patch the function `renv_file_copy_dir_cp` to remove the `-p` flag.
I wonder why permissions are preserved in the first place? Without `-p`, the copied files would be owned by whoever is running the R process, which I assume is the user. Am I correct in assuming that would …

Make `renv_file_copy_dir_cp` not preserve permissions

---

R/roxygen.R

This PR fixes the R command given to overwrite "repos".
> [!NOTE]
> `roxygen2::roxygenise()` has not be ran to avoid possible merge conflicts.

fix: typo in R command to retrieve repositories

---

R/ppm.R
tests/testthat/test-ppm.R

Fixes #1720 
I set out to add support for getting Rocky Linux 9 binaries from Package Manager instances, as it's binary compatible with CentOS/RHEL binaries. This was initially motivated by adding binary support for Connect instances hosted on Rocky. Along the way I went to check out `/etc/os-release` files from other supported distros, and made some other additions/fixes.
Connect's supported distros are listed [here](https://docs.posit.co/connect/admin/), and Package Manager's are available [here](https://packagemanager.posit.co/client/#/repos/cran/setup).
Changes I made:
- Added functions to detect Rocky Linux and AlmaLinux, two CentOS/RHEL-compatible distributions, as `centos8`/`rhel9`.
- Added support for Debian. (It isn't supported by Connect but is by PPM, so it's nice for `renv` to …

Expand PPM platform support

---

NEWS.md
R/ppm.R
tests/testthat/test-ppm.R

Following on from #1728 (also related to #1720), adds support for detecting Amazon Linux 2 as compatible with `centos7` binaries.
Per Amazon's documentation [here](https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html#epel)
> Extra Packages for Enterprise Linux (EPEL) is a project in the Fedora community with the objective of creating a large array of packages for enterprise-level Linux operating systems. The project has primarily produced RHEL and CentOS packages. AL2 features a high level of compatibility with CentOS 7. As a result, many EPEL7 packages work on AL2. However, AL2023 doesn't support EPEL or EPEL-like repositories.
Connect's support for Amazon Linux 2 is based on its support for `centos7` binaries, so I believe this is the right move. Amazon Linux 2023 is not …

Add PPM binary support for Amazon Linux 2

---

inst/config.yml

This PR fixes a typo in the documentation where a word was repeated, *i.e.*, "not not".

fix(config.yml): repeated word typo

---

R/available-packages.R

This addresses a bug introduced in the fix for #1706. 
On 2023-12-05 at 09:21 PST, [I had a successful check for MacOS](https://github.com/carpentries/sandpaper/actions/runs/7104065642/job/19338200777) to ensure that a package added with `renv::record("pkg@version")` would be successfully recorded.
EDIT: for context, this test has been running successfully for several months (see https://github.com/carpentries/sandpaper/commit/0de3543d6041155e8eb9bf3f25d8e73edc37a27d for the last time this particular code was modified)
The very next check on 2023-12-05 at 11:07 PST, [had a failure in MacOS](https://github.com/carpentries/sandpaper/actions/runs/7105183840/job/19341804820)
The relevant portion of the error log reads:
```r
Caused by error in `if (length(indices) < nrow(data)) indices <- …
```

return empty data.frame not NULL in renv_available_packages_success

---

vignettes/packages.Rmd

You can see the broken link formatting here: https://rstudio.github.io/renv/articles/packages.html#testing

Fix link to CI vignette

---

vignettes/ci.Rmd

While trying to leverage caching for GitLab CI, https://github.com/rstudio/renv/issues/348 was _extremely_ valuable (thank you!). Experimenting a bit, I found the variables remaining in this MR to be the minimal set needed to leverage the cache in GitLab's CI.

minimize env vars needed for renv to work on GitLab CI

---

NEWS.md
R/bootstrap.R
R/load.R
R/settings.R
R/zzz.R
inst/resources/activate.R
man/settings.Rd
templates/template-activate.R

By just respecting `RENV_PROJECT` if set.

avoid need for project.id

---

R/settings.R

Otherwise this creates an issue in `renv_settings_updated` as it will use a wrong update function
https://github.com/rstudio/renv/blob/5bc089696a96ca372f1f1ecaf0a0a4167891ed36/R/settings.R#L180-L183

for `settings$ppm.enabled()`, update should be NULL like other settings without config

---

R/use-python.R

Issue was initially found with `use_python()` : using `renv::use_python('.venv\Scripts\python.exe')` would write in the lockfile 
````
"Python": {
"Version": "3.12.1",
"Type": "virtualenv",
"Name": "C:\\Users\\chris\\Documents/DEV_R/quarto-web/.venv"
},
````
Note the `\\` in the path. This should have been relative path and `"Name": ".venv"`. 
It does not happen like this because `"~/DEV_R/quarto-web/.venv"` will be expanded with `path.expand()`. This function will use `R_USER` env var,  which can use `\\` as path separator. Path not starting with `~`  and already normalized going through `path.expand()` would be untouched and use only `/` separators.
So comparison does not work. 
More generally, `path.expand()` will give you `\\` most of the time, unless `R_USER` is pre process which …

Normalize expanded paths before comparaison 

---

README.Rmd
README.md
vignettes/renv.Rmd

I needed a refresher on renv, so I was reading the intro docs and found a few tweaks.

Copy edits

---

R/load.R
R/rstudio.R
R/utils.R

* Tweak the use of RStudio's session init hook to deliver the intent of PR #1652.
* Otherwise, if RStudio and its session init hook aren't available, just emit a message if we discover the need for `renv::restore()` during auto-loading.
To do/discuss:

Refine auto-loading behaviour

---

NEWS.md

I failed to add a bullet to `NEWS.md` in #1880. I've added it here.

Add `renv::lockfile_validate` note to `NEWS.md`

---

R/snapshot.R

Just spotted a small typo on help page. 
Do you need me to re-render `devtools::document()` on the PR ?

typo on doc

---

vignettes/ci.Rmd

A follow-on to #1822 now that I've used `renv` across more complex GitLab CI jobs.
`CI_PROJECT_NAME` (e.g., `dplyr`)  allow for consistent re-use across runs / stages / jobs vs. `CI_JOB_NAME` (e.g., `lint`)

Use `CI_PROJECT_NAME` instead of `CI_JOB_NAME` for GitLab CI vignette

---

R/lockfile.R
R/manifest-convert.R
R/paths.R
tests/testthat/test-lockfile.R

This pull request changes the behavior of `renv_lockfile_load()`, which attempts to load a lockfile from a directory. When no lockfile is found, but a `manifest.json` is found, the manifest is used to automatically generate a lockfile, which is then loaded. The behavior only occurs when the function is called with `strict = FALSE`, the default. If no manifest is present, the function `renv_lockfile_init()` is called, as before. A message is printed when this happens.
I added a supporting function in `paths.R` to return a manifest path, just cribbing from `renv_paths_lockfile()`. However, just doing `file.path(project, "manifest.json")` might be just as good. I'm not sure what the semantics are around path loading, so was just trying to follow existing patterns.
The logic in …

when attempting to load a lockfile and finding only a manifest, automatically generate a lockfile and load that

---

.gitignore
DESCRIPTION
NEWS.md
R/aaa.R
R/call.R
R/cli.R
R/config.R
R/dependencies.R
R/dynamic.R
R/errors.R
R/load.R
R/new.R
R/recurse.R
R/syms.R
tests/testthat/_snaps/dependencies.md
tests/testthat/test-bootstrap.R
tests/testthat/test-call.R
tests/testthat/test-dependencies.R
tests/testthat/test-json.R
tests/testthat/test-recurse.R

Addresses https://github.com/rstudio/renv/issues/1999.

resolve regression in dependencies performance

---

R/embed.R
man/embed.Rd

`embed()` supports `.qmd` files as of https://github.com/rstudio/renv/commit/884569687ed75efa22a4f5b9fd5ab6f75aa9a7c3
However, `.qmd` format is not mentioned in the docs. 
I've not bumped / updated NEWS as you might want to combine with larger changes.

update embed docs to include qmd

---

R/bootstrap.R
inst/resources/activate.R

If renv was bootsraped with a differen RENV_PROJECT environment, the reload would ignore the setting and create renv/ directory in the working directory instead of the project directory.

Pass project to renv_bootstrap_run reloading with the correct project

---

README.Rmd
README.md

This fixes the `R-CMD-check.yaml` badge. The `README` currently has an outdated link and is reporting as failed even though the check is passing.

Fix R-CMD-check badge

---

_pkgdown.yml

Closes #2048.
This seems like the best way to add this function to the reference since the docs need to be filled out a bit more than functions under `@rdname lockfiles`. Happy to change it up if you disagree.

Add `lockfile_validate` to reference

---

vignettes/renv.Rmd

I noticed while doing some work on another branch

Two small typo fixes

---

NEWS.md
R/project.R
R/remotes.R
R/retrieve.R
tests/testthat/helper-aaa.R
tests/testthat/helper-setup.R
tests/testthat/packages/future/DESCRIPTION
tests/testthat/packages/today/DESCRIPTION
tests/testthat/test-install.R
tests/testthat/test-repos.R

Closes https://github.com/rstudio/renv/issues/2071.

tolerate packages requiring newer versions of R

---

NEWS.md
R/aaa.R
R/backports.R
R/bootstrap.R
R/files.R
R/hash.R
R/lockfile-read.R
R/lockfile-write.R
R/lockfile.R
R/record.R
R/snapshot.R
R/zzz.R
inst/resources/activate.R
tests/testthat/_snaps/snapshot.md
tests/testthat/helper-snapshot.R
tests/testthat/test-bioconductor.R
tests/testthat/test-files.R
tests/testthat/test-lockfile.R
tests/testthat/test-snapshot.R
tests/testthat/test-vendor.R

Closes https://github.com/rstudio/renv/issues/2057.
Should we still include a Hash field in the lockfile, or should we recompute hashes on the fly? This mainly comes to mind as the hash would be invalid if the lockfile's fields were changed by a user.
I also wonder if there are any DESCRIPTION fields that we should exclude from the lockfile -- for example, fields like Packaged, Built, and Date/Publication, since those will differ depending on where and how the package was built. (A common request for users was to make sure that packages installed from CRAN, and packages installed from P3M, produced otherwise identical lockfile records.)
Should we include the exact, raw, contents of the DESCRIPTION fields in the lockfile (including newlines)? Or is it okay to normalize that whitespace? (In …

include all required fields for hashing in lockfile

---

R/settings.R

The vignette `cellar` has been renamed to `package-sources` as part of ba4f0c0. This commit updates the reference to the vignette.

Update reference to renamed vignette

---

.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
.github/workflows/pr-commands.yaml
.github/workflows/slow-tests.yaml
vignettes/ci.Rmd

I noticed the version mentioned in the ci.Rmd vignette is a bit out of date, I bumped it there and in the workflows.

Update actions/checkout to v5
